### ISSUE TITLE
Support for .NET 8 isolated

### ISSUE THREAD

**Issue by matsla** [OfficeDev/teams-toolkit#10864]
Creating a teams toolkit project using Visual Studio 2022 the target framework is .NET 6. End of support for .NET 6 is November 12, 2024

When will you support to target framework .NET 8 when you create a teams toolkit project in VS2022?
When will you provide instructions how to upgrade an existing project from .NET 6 to .NET 8 isolated?

**Comment by hund030** [comment]
@matsla Visual Studio 17.9 is now available. We have updated all Teams Toolkit project templates to use .NET 8.0 by default.  [What’s new in Teams Toolkit for Visual Studio 17.9](https://devblogs.microsoft.com/microsoft365dev/whats-new-in-teams-toolkit-for-visual-studio-17-9/)
We do not have migration instructions yet, since there is a serie of official documents about migration you can refer to. [Migrate from ASP.NET Core in .NET 7 to .NET 8](https://learn.microsoft.com/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio)
