### ISSUE TITLE
bug report: provision fails with DownloadBicepCliError

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/teams-toolkit#11723]
While trying to provision a bot from Teams Toolkit extension for VS Code, we get below error:

`Failed to Execute lifecycle provision due to failed action: arm/deploy. DownloadBicepCliError:Unable to download Bicep cli from 'https://api.github.com/repos/Azure/bicep/releases'. The error message was: read ECONNRESET. Fix the error and try again. Or remove the bicepCliVersion config in the config file teamsapp.yml and Teams Toolkit will use bicep CLI in PATH. `

Please suggest.

**Expected behavior**
The bot should be provisioned without error.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 5.0.0

**Comment by xzf0587** [comment]
Hi @nanddeepn,
Thanks for reaching out.
The message showed that the TTK failed to download Bicep cli from 'https://api.github.com/repos/Azure/bicep/releases'. The Bicep cli is used to compile the bicep file under infra folder when executing Provision command.
Since the error message said that `read ECONNRESET` when download process, could you verify whether you can access 'https://api.github.com/repos/Azure/bicep/releases'?

If the network cannot access the download url as design, please follow the steps to config Bicep cli.
1. Download Bicep cli from https://github.com/Azure/bicep/releases
2. Add the Bicep cli path into PATH environment.
3. Remove the line including the BicepCliVersion in teamsapp.yml as below.
![image](https://github.com/OfficeDev/teams-toolkit/assets/16380704/52d43920-785d-43a5-b540-5f89bbf89aba)
