### ISSUE TITLE
bug: ServerError: unauthorized_client: 700016

### ISSUE THREAD

**Issue by smtlaissezfaire** [OfficeDev/teams-toolkit#12101]
**Describe the bug**

Seeing this consistently with a production bot when trying to get teams members.

```
{"code":"Internal","message":"ServerError: unauthorized_client: 700016 - [2024-07-29 21:49:58Z]: AADSTS700016: Application with identifier '[redacted]' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. Trace ID: [redacted] Correlation ID: [redacted] Timestamp: 2024-07-29 21:49:58Z - Correlation ID: [redacted] - Trace ID: [redacted]"}
```

Happy to provide correlation id etc or whatever is needed to debug on your end.

The bot is running in multitenant mode, so not sure why I'd be getting this error.

Note, staging works just fine in a test teams instance.

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

cc @jaymitchell

**Comment by yukun-dong** [comment]
Hi @smtlaissezfaire , this is a issue with botframework rather than teams toolkit. You can open an issue in the botframework repo.

By the way, you could look into this stackoverflow question https://stackoverflow.com/questions/71031057/microsoft-bot-framework-bot-missing-from-bot-framework-tenant-how-to-add, which is similar to yours.
