### ISSUE TITLE
Issue when creating new app using teams toolkit

### ISSUE THREAD

**Issue by Hirend1** [OfficeDev/teams-toolkit#12340]
**Describe the bug**
Issue when creating new app using teams toolkit.

****Intstalled Versions******
VSCode: 1.92.2
node version: 14.18.1
microsoft/generator-sharepoint:1.18.0
microsoft/teamsfx-cli: 2.1.0
yo:4.3.1
gulp :4.0.2

**To Reproduce**

1. Click on Create new app.
2. and execute steps to create an app.
3. when i select use globally spfx version. which is added in screenshot 1 , it show me global spfx version 1.14.0 but in my system spfx version is 1.18.0 when i check version in command line it show me right version 1.18.0 but when creating new app it show me global version 1.14.0 . after that it show me Error in terminal :  
  **[2024-09-05T11:47:03.890Z] [Error] - code:SPFx.DevEnvironmentSetupError, message: Your SPFx development environment is not set up correctly. Click "Get Help" to set up the right environment.
 Help link: https://aka.ms/teamsfx-spfx-dev-environment-setup
[2024-09-05T11:56:09.913Z] [Error] - code: SPFx.DevEnvironmentSetupError, message: Your SPFx development environment is not set up correctly. Click "Get Help" to set up the right environment.
 Help link: https://aka.ms/teamsfx-spfx-dev-environment-setup**

4. after that i have check spfx and node version everything is right and older project that is working but when creating new project, it show error which is in screen shot 2
5. See error images
6. screenshot 3 is version in my pc.

**Screenshots**
![image](https://github.com/user-attachments/assets/1ae184ac-2f35-4049-8568-7e986021e7fb)
![image](https://github.com/user-attachments/assets/97325727-6c8d-4e6a-b555-a04f9912db5b)
![image](https://github.com/user-attachments/assets/032e1121-d076-4acb-8d94-924cc6f4a3f9)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Hirend1, thanks for reporting this to us! 
Regarding your questions, 
1> The description of 'Use globally installed SPFx' is indicating  that supported lowest version is SPFx v1.14.0 and users should use v1.14.0 or higher to make it work in TTK. 
2> Since you're having SPFx v1.18.0, Node v16 or v18 is required as documented in SPFx side https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility. Please upgrade your Node version and try again.

**Comment by Hirend1** [comment]
Hello,
I have already installed globally SPFx version which is 1.18.0. and node version is 14.18.1. when create a new app it show me globally SPFx version  1.14.0. see the below image.
![image](https://github.com/user-attachments/assets/4cad7a43-89dc-412f-beaf-6c71164f1582)
when create in app this show me below error:
![image](https://github.com/user-attachments/assets/c0b9f3bb-2d23-4ab5-9493-1e86eb225a47)
and check version using terminal it show me correct version of all see the below image
![image](https://github.com/user-attachments/assets/2faf9234-18bf-474d-aed1-53d5015b9d0c)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Hirend1 Please **do read** my comments. The **version v1.14.0 is not indicating that your globally installed version is v1.14.0**. It just means lowest supported version is v1.14.0. Node v14 is not supported for SPFx v1.18.0, you'll need to upgrade to v16 v18 to avoid potential issue.

**Comment by Hirend1** [comment]
Hello,
I have upgrade  node version 18.20.3 and SPFx version 1.19.0  and creating app using team Toolkit  still app is not created it show me below error.
![image](https://github.com/user-attachments/assets/44402d43-0ad5-4dbc-bd29-7aa6bee76352)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Hirend1, thanks for trying this out. Could you help attach the TTK version you're using since recently we have a fix on [similar issue](https://github.com/OfficeDev/teams-toolkit/issues/12143). You can use latest pre-release version to avoid the error in case the version is the one with that bug.
