### ISSUE TITLE
Create configurable frontend start task

### ISSUE THREAD

**Issue by thorsten** [OfficeDev/teams-toolkit#4084]
**Is your feature request related to a problem? Please describe.**
Our Teams App project is using a based Nx mono repo and we want to use all Nx commands. Currently this is not possible as TeamsFX relies on the hard coded react-scripts execution:

https://github.com/OfficeDev/TeamsFx/blob/483a4e129b9ec7c34f3b93f7d593ac2b363fd697/packages/fx-core/src/common/local/taskDefinition.ts#L26

Using a custom command in Nx does not solve the issue as depending on "react-scripts" avoids using alias imports. We need alias imports in tsconfig.json for the usage of shared Nx libraries to avoid duplicate code.

Therefore we want to remove the whole "react-scripts" dependency.

**Describe the solution you'd like**
A configurable frontend start command in localSettings.json file would be awesome to avoid the hard dependency of the "npx react-scripts" call in the frontend start task.

**Describe alternatives you've considered**
Overwriting the local "npx react-scripts" command via bash function didn't work and is not a suitable solution for the future as it needs to be configured outside of the project.

Thank you very much!

**Comment by kuojianlu** [comment]
@thorsten Thanks for your feature request. The start scripts customization is under our consideration and we released this feature in Teams Toolkit 3.4.0. You can use the latest version to **create a new project** and it will meet your requirement. The changes in the new version are:
1. Add a `dev:teamsfx` script in package.json, like
```json
    "scripts": {
        "dev:teamsfx": "env-cmd --silent -f .env.teamsfx.local npm run start",
        "start": "react-scripts start",
    },
```
2. Instead of hard coding the command as `npx react-scripts start` in code, use `npm run dev:teamsfx` in tasks.json to start the task. So you can update the `start` script as your needs.

A whole latest sample can be seen [here](https://github.com/OfficeDev/TeamsFx-Samples/tree/kuojianlu/localdebug/hello-world-tab). Let me know if you have any questions :)

**Comment by thorsten** [comment]
@kuojianlu Thank you very much!

Yes, it works via VS Code. In our case we're using it via teamsfx-cli and not via VS Code. (Background info: we're running E2E tests for our Teams app via Playwright on Azure DevOps.

How is it possible to use the commands above from the teamsfx-cli? There it seems to be hardcoded as it always uses "npx react-script start".

Thank you very much in advance!

**Comment by kuojianlu** [comment]
@thorsten Excited to know that you use teamsfx-cli and Playwright to run E2E test for a Teams app! We considered the same thing. What we did is using [vscode-extension-tester](https://github.com/redhat-developer/vscode-extension-tester) to start debugging then using Playwright to test.

For teamsfx-cli we just released [v0.11.1](https://www.npmjs.com/package/@microsoft/teamsfx-cli/v/0.11.1), which also supports the start scripts customization. Please try it and let me know if you have any questions :)

**Comment by thorsten** [comment]
@kuojianlu Thanks for the release, we'll test the next days.

**Comment by knoefel** [comment]
@thorsten Thx for opening this thread!

I'm facing the same problem right now as i'm trying to integrate teams into an existing react nx repo. I'm a little bit lost right now where to put the teams config files, did you put everything at the root folder, or within the `apps/{app-name}` directory? 

Is there maybe any resource on how to integrate nx with teams? Unfortunately i didn't find anything related. 

Thx in advance for any feedback or tip!!

**Comment by zamarawka** [comment]
@knoefel faced with this problem too.
I placed all fx files in separate directory and use [this feature](https://github.com/OfficeDev/TeamsFx/issues/4084#issuecomment-1056102196) to link cli with my main app 
To link npm scripts without duplications I use
```
npm run --prefix <path/to/directory/with/package.json/file> start
```

But anyway, at now add fx to existing app is really painful...

**Comment by MuyangAmigo** [comment]
Hey @thorsten and @zamarawka , thanks for reaching out! Our team has feature planned to help add "fx" (meaning TeamsFx required configurations and manifest template) into existing applications/directory via `teamsfx init`, we will ship a preview feature in early April and would love to see your feedback. Please stay tuned with us :)

**Comment by thorsten** [comment]
@MuyangAmigo wow, awesome news, looking forward for the April release!

**Comment by AndrewCraswell** [comment]
Something I've encountered on our app is that the added time to start the Teams app in debug, which happens after Create React App builds the app -- takes a very long time. As our app has grown, CRA build times became very very long. One of my goals after switching to Teams Toolkit was to also swap out the CRA toolchain for [Vite](https://vitejs.dev/). After trying this, the build times indeed came down dramatically, and the developer experience was great. However, I couldn't get Teams Toolkit to integrate with Vite. There seems to be too many hardcoded assumptions made in the Teams Toolkit code.

1. The PORT being set to 53000 was the first hurdle. Luckily with some tweaking in the Vite config, I was able to overcome this. But I'm looking forward to a future update where Teams Toolkit doesn't assume port 53000.
2. The second issue is that internally, the Toolkit assumes important environment variables begin with "REACT_". However, Vite uses a different prefix: "VITE_". The toolkit automatically generates variables with the "REACT_" prefix, which won't be discovered when Vite loads the environment variables.
3. Third issue I hit was related to the start task. Based on the discussion above, I was able to configure it to run the Vite start task instead of the CRA task. However, when the build completes and initiates watch mode, the Toolkit never launches the browser window to view the app. But when I terminate the Vite start process on the command line, only then will the Toolkit launch the browser window.

It seems like there's enough things that need to be configurable, that the Teams Toolkit extension should get a VS Code extension settings page where these values can get configured:

- Environment variable prefix (default: "REACT_")
- Start task (default: "react-scripts start")
- Port (default: 3000)
- Https (default: Yes)
- Hostname (default: "localhost")

The problem of course, is that each toolchain (CRA, Vite, etc) might set these settings differently.

**Comment by richw-kai** [comment]
We're looking at using Vite for our setup, and actually hoping to move away from using React and use Vue.js for our frontend. I'm facing the same problem where the startup using vs code toolkit will pause until I terminate the terminal session that Vite has run in - and at this point it will open up the Teams app in a browser - of course it is too late here - I'm wondering if there is a specific signal in the CRA series of commands you listen for that Vite watch mode isn't firing?

When using the fx cli I face the same issue but of course the Vite command is backgrounded so I have no way of starting it.

Any thoughts would be appreciated for getting the teamsfx working with Vite as I think it will increase developer productivity greatly!

**Comment by MuyangAmigo** [comment]
Hey folks, thanks a lot for providing these great feedbacks to us. We have added those into our backlog and will come back for updates!

**Comment by MuyangAmigo** [comment]
@sylvesteraswin Have you had any chance to give the latest Teams Toolkit (V4.1.1) a try? We have added the support to [customize the behavior of local debug](https://aka.ms/teamsfx-debug-tasks). For example you could change the `Start frontend` section with the command you want to use with `vite` and make sure to update the `endsPattern` so VS Code knows when commands execution is done and will open the browser. 

Let us know if you face further challenges. CC: @swatDong @jidddddd

**Comment by Ratomir** [comment]
Hi all,

We have the mono repo with the nx too.  The example with the hello-tab and react hello world made with the nx cli is published on my repository, https://github.com/Ratomir/teams-toolkit-with-nx 
The teams application is under the apps/rvsteams folder. I moved the fx files to the root of the repository so that the teams toolkit can understand that there is the teams project. 
Also, I modified the Start frontend task to run the teams app with the nx, maybe I am doing it wrong, but I am not sure.
@kuojianlu  I couldn't find your example with the nx, sorry.
Not sure, but I believe that the hello-tab example with the nx would be much more than beneficial for the community, I am willing to help. Not sure in which direction to go to not miss something crucial in the beginning and finish it with the wrong concept. I am sure that your help will be welcome with a good foundation.

Kind regards, :)

**Comment by kuojianlu** [comment]
@Ratomir Sorry for the late reply. I think your example is not completely compatible with Teams Toolkit. When debugging (F5), Teams Toolkit will generate `tabs/.env.teamsfx.local` and write the environment variables for tab app to this file. The command of your "Start frontend" task is `npx nx run rvsteams:serve --verbose`, will it consume the environment variables in `tabs/.env.teamsfx.local`?

We are refactoring Teams Toolkit, making it more transparent and customizable. I believe it will be easier to develop a mono repo with Teams Toolkit then.

**Comment by ludes2** [comment]
Hello everyone, has anyone found a solution to the problem? I have a TeamsFx application that was created with the Teamstoolkit v5 and I have implemented everything as described by @cleferman . The browser opens in Teams, but apparently there is a problem with the index.html.
![viteTabIndexhtmlerror](https://github.com/OfficeDev/TeamsFx/assets/17458678/fe6cfe86-610f-4f86-b0c5-cd5f6d639515)

Does somebody has any idea?

**Comment by kuojianlu** [comment]
@ludes2 Please verify:
1. Did the tab app start successfully?
2. Did you use the SSL certificate in your tab app?

Please note that Teams Toolkit provides the ability to generate and set the SSL certificate for tab app, i.e., the `devTool/install` action in `teamsapp.local.yml`.

**Comment by MuyangAmigo** [comment]
Addressed in the latest Teams Toolkit.
